version: "2.2"
services:
  # https://hub.docker.com/r/intersystems/iris-community
  iris:
    container_name: my-iris
    init: true
    build: .
    volumes:
      - ./:/opt/irisapp
    ports:
      - 9092:52773
      - 9091:1972

  java-gateway:
    container_name: java-gateway
    image: java-gateway
    build: chat-gpt-service
    environment:
      - CHATGPT_API_KEY=Key
    ports:
      - 55555:55555