version: "2.2"
services:
  # https://hub.docker.com/r/intersystems/iris-community
  iris:
    container_name: my-iris
    init: true
    build: .
    volumes:
      - ./:/opt/irisapp
    ports:
      - 9092:52773
      - 9091:1972

  java-gateway:
    container_name: java-gateway
    image: java-gateway
    build: chat-gpt-service
    ports:
      - 55555:55555
    env_file: .env

#  starchat:
#    build:
#      context: .
#      dockerfile: starchat.Dockerfile
#    ports:
#      - "3000:3000"
#    env_file: .env